config/routes.rb
Rails.application.routes.draw do

  resources :users

  resources :appointments do
    resources :reviews, only: [:new, :create]
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  root 'sessions#new'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :reviews, foreign_key: :author_id

  validates :full_name, :email, presence: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  validates_format_of :phone_number, :with => /\A\d{3}-\d{3}-\d{4}\z/, :on => :create

  def past_appointments
    self.appointments.find_all{|appt| appt.past?}.sort{|a,b| a.start_time <=> b.start_time}
  end

  def reviewed_past_appointments
    self.appointments.find_all{
      |appt|!!appt.reviews.find{|review| review.author_id == self.id}}
      .sort{|a,b| a.start_time <=> b.start_time}
  end

  def unreviewed_past_appointments
    self.past_appointments - self.reviewed_past_appointments
  end

  def future_appointments
    self.appointments.find_all{|appt| !appt.past?}.sort{|a,b| a.start_time <=> b.start_time}
  end

  def booked_appointments
    self.future_appointments.find_all{|appt| appt.booked?}
  end

  def next_booked_appointment
    self.booked_appointments.first
  end

  def open_appointments
    self.future_appointments.find_all{|appt| appt.open?}
  end

  def unbooked_past_appointments
    self.past_appointments.find_all{|appt| appt.open?}
  end

  def received_reviews
    self.past_appointments.map {|appt| appt.reviews.find{|rev| rev.author_id != self.id}}.compact
  end

  def average_rating
    unless self.received_reviews.empty?
      self.received_reviews.reduce(0){|sum, rev| sum + rev.rating.to_i} / self.received_reviews.length
    else
      "no reviews yet"
    end
  end

  def stars_received
    self.received_reviews.reduce(0){|sum, rev| sum + rev.rating.to_i}
  end

  def karma
    self.stars_received + self.reviews.count
  end

    def can_book(appointment)
    type == "Student" && !self.appointments.any?{ |booking| (appointment.start_time >= booking.start_time && appointment.start_time < booking.end_time) || appointment.end_time > booking.start_time && appointment.end_time <= booking.end_time}
  end

  def has_not_reviewed(appt)
    appt.reviews.none?{|review| review.author_id == self.id}
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      @errors = @user.errors.full_messages
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def show
    if logged_in?
      @user = User.find_by(id: params[:id])
      if @user
        render 'show'
      else
        redirect_to appointments_path
      end
    else
      redirect_to root_path
    end
  end

  def destroy
    @user = User.find_by(id: params[:id])
    if logged_in? && current_user = @user
      @user.destroy
      redirect_to root_path
    else
      redirect_to user_path(@user)
    end
  end

  private
  def user_params
    params.require(:user).permit(:full_name, :email, :password, :photo_path, :phone_number, :type)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div class="form-group">
  <h1 id="sign-up-header">Sign Up</h1>

  <% if @errors %>
  <ul>
    <% @errors.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>

  <%= form_tag(users_path, method: 'post') do %>
    <ul>
      <li>
        <%= label_tag 'full_name' %><br />
        <%= text_field_tag "user[full_name]" %>
      </li>
       <li>
        <%= label_tag :photo_path %><br />
        <%= text_field_tag "user[photo_path]" %>
      </li>
       <li>
        <%= label_tag :phone_number %><br />
        <%= text_field_tag "user[phone_number]", nil, placeholder: "xxx-xxx-xxxx" %>
      </li>
       <li>
        <%= label_tag :type %><br />
        <%= select_tag 'user[type]', "<option>Student</option><option>Mentor</option>".html_safe %>
      </li>
      <li>
        <%= label_tag :email %><br />
        <%= text_field_tag 'user[email]', nil, placeholder: "email@email.com" %>
      </li>
      <li>
        <%= label_tag :password %><br />
        <%= password_field_tag 'user[password]' %>
      </li>
       <li><%= submit_tag('Register', :class => "btn btn-warning") %></li>
    </ul>
  <% end %>
</div>

app/views/users/show.html.erb
<div id="contact-info">
  <h3>Phone Number: </h3>
    <%= @user.phone_number %>
  <h3>Email: </h3>
    <%= @user.email %>
</div>


<% if @user.type == "Mentor" %>
<div id="stats">
  <div class="stat">
    <h3>Karma: </h3>
    <%= @user.karma %>
  </div>
  <div class="stat">
    <h3>Average Rating: </h3>
    <%= @user.average_rating %>
  </div>
  <div class="stat">
    <h3>Total Appointments: </h3>
    <%= @user.past_appointments.count %>
  </div>
    <div class="stat">
    <h3>Member Since: </h3>
    <%= @user.created_at = format_time_for_visibility(@user.created_at) %>
  </div>
</div>
<% end %>

<% if current_user.id == @user.id %>
  <div id="center-show-name">
  <h2>Welcome, <%=@user.full_name%>! </h2>
</div>
<% else %>
  <div class="center-show-visitor">
  <h2>Welcome to <%=@user.full_name%>'s Profile!</h2>
  <br><br>
<% end %>

  <% if @user.type == "Student" && current_user != @user %>
    <p><%=@user.full_name%> is a student!</p>
  <% end %>
</div>


  <br><br>

  <% if current_user.type == "Student" && @user.type == "Mentor" %>
    <div class="appt-block">
    <h2>Future Appointments</h2>
      <ul class="center-list">
        <%@user.appointments.each do |appt| %>
        <li><h1><%=link_to appt.start_time = format_time_for_visibility(appt.start_time), appointment_path(appt) %></h1>
        <p>With <%=appt.mentor.full_name%>: Phase <%=appt.phase%></p></li>
      <%end%>
      </ul>
  </div>
  <% end %>

  <% if current_user.id == @user.id %>
  <div class="appt-block">
    <h2>My Future Appointments</h2>
      <ul class="center-list">
        <%@user.appointments.each do |appt| %>
        <li><h1><%=link_to appt.start_time = format_time_for_visibility(appt.start_time), appointment_path(appt) %></h1>
        <p>With <%= link_to appt.mentor.full_name, user_path(appt.mentor) %>: Phase <%=appt.phase%></p></li>
      <%end%>
      </ul>
  </div>

  <br> <br>


  <div class="appt-block">
    <h2>My Past Appointments</h2>
      <ul class="center-list"><%@user.appointments.each do |appt| %>
        <% if appt.past?%>
          <%= "#{appt.start_time = format_time_for_visibility(appt.start_time)} with #{appt.mentor.full_name}" %>
          <% if @user.has_not_reviewed(appt) %>
            <li><%= link_to "Review this session", new_appointment_review_path(appt) %></li>
            <li>My Notes: <%=appt.notes%></li>
          <% end %>
        <li>Review for me: </li>
        <%if review = current_user.received_reviews.find{|review| review.appointment_id == appt.id } %>
          <p><%= review.body %></p>
          <% else %>
          <p> No reviews yet! </p>
          <%end%>
        <%end%>
      <%end%>
    </ul>
  </div>
  <% end %>

</div>
<% if current_user == @user %>
  <div id="delete-account">
    <%= link_to 'Deactivate your account', user_path(@user), method: :delete %>
  </div>
<% end %>