config/routes.rb
Rails.application.routes.draw do

  resources :users

  resources :appointments do
    resources :reviews, only: [:new, :create]
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  root 'sessions#new'

end

app/views/shared/_footer.html.erb
<footer>
  <h6><strong>Created by: Jackie Feminella, Julia Giraldi, Daniel Homer and John Seo</strong></h6>
  <h6><strong>2016</strong></h6>
</footer>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default">

  <ul class="nav navbar-nav">
    <% if logged_in? %>
        <nav class="navbar-brand"><%= link_to "There's a Board", appointments_path %></nav>
    <% else %>
        <nav class="navbar-brand"><%= link_to "There's a Board", new_user_path %></nav>
    <% end %>

    <% if current_user %>
    <nav class="navbar-text navbar-right navbar-link"><%= link_to "Logout", logout_path, method: :delete %></nav>
    <nav class="navbar-text navbar-right navbar-link"><%= link_to current_user.full_name, root_path %></nav>
    <nav class="navbar-text navbar-right navbar-link"><%= link_to "Available Sessions", appointments_path %></nav>
    <% else %>
    <nav class="navbar-text navbar-right navbar-link"><%= link_to "Log In", login_path %></nav>
    <nav class="navbar-text navbar-right navbar-link"><%= link_to "Register", new_user_path %></nav>
    <%end%>

    <% if logged_in? && current_user.type == "Mentor" %>
    <nav class="navbar-text navbar-right navbar-link"><%= link_to "New Tutoring Session", new_appointment_path %></nav>
    <% end %>
  </ul>

  <% if logged_in? && current_user.type == "Mentor" %>
    <span id="portal">MENTOR PORTAL</span>
  <% end %>
  <% if logged_in? && current_user.type == "Student" %>
    <span id="portal">STUDENT PORTAL</span>
  <% end %>

  <img id="icon-nav" src="<%=image_path("board-icon.png")%>">


</nav>