config/routes.rb
Rails.application.routes.draw do

  resources :users

  resources :appointments do
    resources :reviews, only: [:new, :create]
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  root 'sessions#new'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :mentor, class_name: 'User'
  belongs_to :student, class_name: 'User'
  has_many :reviews
  has_and_belongs_to_many :topics

  validates :start_time, :length, :phase, presence: true
  validate :cannot_end_before_it_starts, :cannot_overlap_existing_user_appointment
  validate :cannot_start_in_the_past
def end_time
  start_time + length.to_i.minutes
end

def open?
  !student_id && !self.past?
end

def booked?
  !self.open?
end

def past?
  self.end_time < DateTime.now.utc
end

def list_topics
  self.topics.reduce(""){ |string, topic| string + "| " + topic.name + " "}
end

private

def cannot_end_before_it_starts
  if start_time - self.end_time > 0
    errors.add(:end_time, "cannot be before the start time.")
  end
end

def cannot_start_in_the_past
  if start_time < DateTime.now.utc
    errors.add(:start_time, "cannot be in the past.")
  end
end

def cannot_overlap_existing_user_appointment
  potential_conflicts = User.find(student_id || mentor_id).appointments
  if potential_conflicts.any?{
    |appt| start_time >= appt.start_time && start_time < appt.end_time }
    errors.add(:start_time, "overlaps with one of your existing commitments.")
  elsif potential_conflicts.any?{ |appt| self.end_time > appt.start_time && self.end_time <= appt.end_time}
      errors.add(:end_time, "overlaps with one of your existing commitments.")
  end
end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  include AppointmentsHelper

  def index
    if !logged_in?
      redirect_to root_path
    else
      @phase = params[:phase]
      @user = User.find_by(id: session[:user_id])
      @next_appointment = User.find_by(id: session[:user_id]).next_booked_appointment
      @phase = params[:phase]
      @appointments_by_phase = open_appts_where_phase_is(@phase)
      @appointments = Appointment.all
    end
  end

  def new
    if !logged_in?
      redirect_to root_path
    else
      @appointment = Appointment.new
      @topics = Topic.all
    end
  end

  def create
    @appointment = Appointment.new(appointment_params)
    @appointment.mentor_id = current_user.id
    if params[:appointment][:topics]
      @appointment.topics << Topic.find(params[:appointment][:topics])
    end
      @appointment.start_time = combine_date_time(params[:date], params[:time])
    # @topics = Topic.all
    if @appointment.save
      redirect_to appointment_path(@appointment)
    else
      @errors = @appointment.errors.full_messages
      render 'new'
    end
  end

  def show
    if !logged_in?
      redirect_to root_path
    else
      @appointment = Appointment.find_by(id: params[:id])
      @user = User.find_by(id: session[:user_id])
      if @appointment
        @appointment.start_time = format_time_for_visibility(@appointment.start_time)
      else
        redirect_to appointments_path
      end
    end
  end

  def update
    @appointment = Appointment.find_by(id: params[:id])
    if @appointment.open?
      @appointment.assign_attributes(student_id: current_user.id)
      if @appointment.save
        redirect_to root_path
       else
        @errors = @appointment.errors.full_messages
      end
    else
      @errors = "This appointment was already booked."
    end
  end

  private

  def combine_date_time(date, time)
    dt = "#{date} #{time}"
    DateTime.parse(dt).utc.change(:offset => "-0400")
  end

  def appointment_params
    params.require(:appointment).permit(:start_time, :length, :notes, :phase, :status)
  end

end

app/helpers/appointments_helper.rb
module AppointmentsHelper


  def open_appointments
    Appointment.all.find_all{|a| a.open?}
  end

  def open_appts_where_phase_is(phase)
    phase ? open_appointments.find_all{|a| a.phase == phase.to_i} : open_appointments
  end

  def format_time_for_visibility(time)
    time.in_time_zone("Eastern Time (US & Canada)").strftime("%A, %b %d, %Y %I:%M %p %Z")
  end
end

app/views/appointments/_appointment.html.erb
<li class="appt-listing">
    <h1 ><%=link_to appointment.start_time = format_time_for_visibility(appointment.start_time), appointment_path(appointment) %></h1>
    <p>With <%=appointment.mentor.full_name%>: Phase <%=appointment.phase%> <%= appointment.list_topics %>
      <% if appointment.booked? %>
        | Booked by <%= appointment.student.full_name %>
      <% elsif @user.can_book(appointment) %>
        | <%= link_to "book this appointment", appointment_path(appointment), method: :put %>
      <% elsif @user.type == "Student" %>
        | *conflicts with one of your bookings*
      <% end %>
    </p>
  </li>

app/views/appointments/create.html.erb
<h3>Select Topics!</h3>

app/views/appointments/index.html.erb
<div id="sort-tabs">
  <ul>
    <li>Show by mentor phase:</li>
    <% 5.times do |i| %>
    <li><%=link_to i, appointments_path(phase: i)%></li>
    <% end %>
    <li><%=link_to "view all", appointments_path(phase: nil)%></li>
  </ul>
</div>


<div id="next_appointment">
  <h1>Your next booked appointment: </h1>
  <% if @next_appointment %>
    <%= render @next_appointment %>
  <% else %>
    <p>You don't have any upcoming appointments :(<p>
  <% end %>
</div>

<div class="center-show">

<h1>Available Appointments For
  <% if @phase %>
    <%= "Phase #{@phase}"%>
  <% else %>
  All Phases
  <% end %>
</h1>
  <ol class="center-list">
  <%@appointments_by_phase.each do |appt|%>
    <%= render appt %>
  <% end %>
  </ol>
</div>

app/views/appointments/new.html.erb
<div id="create-session">
  <h1 id="sign-up-header-session">New Tutoring Session</h1>

  <% if @errors %>
  <ul>
    <% @errors.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>

  <%= simple_form_for(@appointment, html: {class: "form-horizontal"}) do |f| %>
    <strong>Date: </strong><input type='date' name= 'date' />
    <strong>Time: </strong><input type='time' name= 'time' />


    <%= f.input :length, collection: ["30", "60"], input_html: {multiple: false} %>

    <% if @topics && @topics.length > 0 %>
    <strong>Topics:</strong>
      <% @topics.each do |topic| %>
      <%= check_box_tag "appointment[topics][]", topic.id %>
      <%= topic.name %>
      <% end %>
    <% end %>

    <%= f.input :notes, label: "Notes", input_html: {class: "form-control"} %>
    <%= f.input :phase, collection: ["0", "1", "2", "3", "4"], input_html: {multiple: false}  %>


    <%= f.button :submit, {:class => "btn btn-warning"}%>
  <% end %>
</div>

app/views/appointments/show.html.erb
<div id="appt_show_div">
  <h1><%=@appointment.start_time = format_time_for_visibility(@appointment.start_time)%></h1>

  <h3> Mentor: <%= link_to @appointment.mentor.full_name, user_path(@appointment.mentor)%></h2>
  <% if @appointment.booked? %>
    <h3>Booked by: <%= link_to @appointment.student.full_name, user_path(@appointment.student)%></h3>
  <% elsif current_user.type == "Student" %>
    <%= link_to "book!", appointment_path(@appointment), method: :put %>
  <% end %>
  <h3> Topics covered:</h3> |
    <% @appointment.topics.each do |topic| %>
      <%= topic.name %> |
    <% end %>
  </h3>


  <% if @appointment.past? %>
    <%= link_to "Review this session", new_appointment_review_path(@appointment) %>
  <% end %>

    <% if @errors %>
    <ul>
      <% @errors.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    <% end %>

</div>